name: AuthPlugin
version: ${project.version}
main: de.marvinleiers.authplugin.AuthPlugin
api-version: 1.16
authors: [ Marvin_Leiers, Marvin2k0 ]
website: www.marvinleiers.de

commands:
  register:
  login:
